Exclude vendor to fix build break
As per https://github.com/jekyll/jekyll/issues/2938#issuecomment-56237068

to fix error:

Configuration file: /srv/_config.yml
            Source: /srv
       Destination: _site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: could not read file /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.6/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.6/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.6/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.